name: Build
on:
  push:
  pull_request:

env:
  REGISTRY: ghcr.io
  # OWNER: ${{ github.repository_owner }}
  OWNER_IMAGE: ${{ github.repository }}
  # Set to "" to publish container on tags only
  # Set to "<branch-name>" to also publish on every push to <branch-name>
  PUBLISH_BRANCH: "main"
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  container:
    name: Container
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Decide whether to push image to registry
        id: publish
        run: |
          PUSH=false
          if [ "${{ startsWith(github.ref, 'refs/tags/') || (github.ref == format('refs/heads/{0}', env.PUBLISH_BRANCH)) }}" = "true" ]; then
            if [ "${{ github.event_name }}" = "push" ]; then
              PUSH=true
            fi
          fi
          echo "push=$PUSH" >> $GITHUB_OUTPUT

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v6
        with:
          flavor: latest=auto
          images: ${{ env.REGISTRY }}/${{ env.OWNER_IMAGE }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to container registry
        uses: docker/login-action@v4
        if: >
          github.event_name == 'push' &&
          (github.ref == format('refs/heads/{0}', env.PUBLISH_BRANCH) ||
          startsWith(github.ref, 'refs/tags/'))
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push to container registry
        uses: docker/build-push-action@v7
        with:
          # Needed so that .git directory is available to embed version info
          platforms: ${{ env.PLATFORMS }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: ${{ steps.publish.outputs.push }}
          # Don't use cache if this image will be published
          cache-from: ${{ steps.publish.outputs.push == 'false' && 'type=gha' || '' }}
          cache-to: ${{ steps.publish.outputs.push == 'false' && 'type=gha,mode=max' || '' }}
